name: CI
on:
  push:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ./Dockerfile
          push: true
          tags: ghcr.io${{ github.organization }}/${{ github.repository }}:latest
          output: type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image
